name: Function App Build and Deploy

on:
  push:
    branches:
      - "main" 
    paths:
        - "SearchDemoAPI/**"
        - "SearchDemoShared/**"
        - ".github/workflows/funcapp.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  provision-service-bus:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
