name: SWA1 App Build and Deploy Static Web App

on:
  push:
    branches:
      - "main" 
    paths:
        - "SearchDemoSWA1/**"
        - "SearchDemoSWA1API/**"
        - "SearchDemoShared/**"
        - ".github/workflows/swa1.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:

      # Checkout code
    # - uses: actions/checkout@v3
    #   with:
    #     submodules: true

      # Log into Azure
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Get SWA Token
      id: swa-token
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: echo SWA_TOKEN=$(az staticwebapp secrets list --name ${{ vars.RESOURCE_NAME }}swa1 --query 'properties.apiKey') | tr "\"" "" >> "$GITHUB_OUTPUT"

    - name: Show Token
      run: echo "token:${{ steps.swa-token.outputs.SWA_TOKEN }}"
  
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ steps.swa-token.outputs.SWA_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
        action: "upload"
        ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
        # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
        app_location: "SearchDemoSWA1" # App source code path
        api_location: "SearchDemoSWA1API" # Api source code path - optional
        output_location: "wwwroot" # Built app content directory - optional
        ###### End of Repository/Build Configurations ######
