name: SWA1 App Build and Deploy Static Web App

on:
  push:
    branches:
      - "main" 
    paths:
        - "SearchDemoSWA1/**"
        - "SearchDemoSWA1API/**"
        - "SearchDemoShared/**"
        - ".github/workflows/swa1app.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
